global using AutoMapper;
global using FluentValidation;
global using FluentValidation.Resources;
global using MediatR;
global using Microsoft.Extensions.DependencyInjection;
global using System.Globalization;
global using System.Reflection;
global using System.Security.Claims;
global using Microsoft.Extensions.Logging;