global using System.Security.Claims;
global using System.Linq.Expressions;
global using MediatR;
global using FluentValidation;
global using FluentValidation.Resources;
global using System.Globalization;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
global using AutoMapper;
